// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCccw9356q__YxO3jbyITr5qKFJbwBz_w4',
    appId: '1:259583360737:android:327438a0b2ccd6df1d41a0',
    messagingSenderId: '259583360737',
    projectId: 'consulta-617fc',
    storageBucket: 'consulta-617fc.firebasestorage.app',
  );
}
